image: docker.porscheinformatik.com/builders/default

stages:
  - build
  - deploy-review
  - acceptence-tests
  - deploy-production
  - cleanup

variables:
  OPENSHIFT_SERVER: https://manage.ocp.porscheinformatik.cloud:8443/
  OPENSHIFT_DOMAIN: ext.ocp.porscheinformatik.cloud
  OPENSHIFT_PROJECT: poi-user-koc
  DOCKER_REGISTRY: docker.porscheinformatik.com
  # Configure these variables in Secure Variables:
  # DOCKER_REGISTRY_USER
  # DOCKER_REGISTRY_PASSWORD
  # OPENSHIFT_TOKEN

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/koc/angular-spring-heroes:$CI_COMMIT_REF_SLUG" .
    - docker push "$DOCKER_REGISTRY/koc/angular-spring-heroes:$CI_COMMIT_REF_SLUG"

.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN"
    - oc project $OPENSHIFT_PROJECT
    - helm init --upgrade --tiller-namespace ${OPENSHIFT_PROJECT} --service-account tiller
    - helm repo add porscheinformatik https://helm-charts.int.ocp.porscheinformatik.cloud
    - |
      function deploy_name() {
        if [[ "$CI_COMMIT_REF_SLUG" == "master" ]]; then
          name='prod'
        else
          name="$CI_COMMIT_REF_SLUG"
        fi
        name=${name:0:45}
        name=${name%-}
        echo "ash-$name"
      }
  script:
    - helm upgrade -i --tiller-namespace ${OPENSHIFT_PROJECT} $(deploy_name) -f deploy/${HELM_VALUES} --set appVersion="v`date +'%Y%m%d-%H%M%S'`" --set image.tag=$CI_COMMIT_REF_SLUG --set route.host=$APP_HOST --set postgresql.postgresPassword="${POSTGRESQL_PASSWORD}" porscheinformatik/web-application

deploy-review:
  <<: *deploy
  stage: deploy-review
  variables:
    APP_HOST: ash-$CI_COMMIT_REF_SLUG.$OPENSHIFT_DOMAIN
    HELM_VALUES: "values-review.yaml"
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://ash-$CI_COMMIT_REF_SLUG.$OPENSHIFT_DOMAIN
    on_stop: stop-review
  only:
    - branches
  except:
    - master

acceptence-tests:
  image: cypress/base:10
  stage: acceptence-tests
  variables:
    CYPRESS_baseUrl: https://ash-$CI_COMMIT_REF_SLUG.$OPENSHIFT_DOMAIN
  before_script:
    - cd heroes-acceptence-tests
    - npm i
  script:
    - npm test
  only:
    - branches
  except:
    - master
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - heroes-acceptence-tests/cypress/videos

deploy-production:
  <<: *deploy
  stage: deploy-production
  variables:
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
    HELM_VALUES: "values-prod.yaml"
  when: manual
  environment:
    name: production
    url: https://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master

stop-review:
  <<: *deploy
  stage: cleanup
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - helm --tiller-namespace ${OPENSHIFT_PROJECT} delete $(deploy_name) --purge
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
