image: docker.porscheinformatik.com/eenv/builders/default:jdk-11

stages:
  - build
  - deploy
  - acceptence-tests
  - deploy-idle
  - cleanup

variables:
  OPENSHIFT_SERVER: https://manage.ocp.porscheinformatik.cloud:8443/
  OPENSHIFT_DOMAIN: ext.ocp.porscheinformatik.cloud
  # OPENSHIFT_PROJECT: poi-user-koc
  CI: "true"
  # Configure these variables in Secure Variables:
  # DOCKER_REGISTRY_USER
  # DOCKER_REGISTRY_PASSWORD
  # OPENSHIFT_TOKEN

maven-test:
  stage: acceptence-tests
  script:
    - mvn test
  artifacts:
    reports:
      junit: junit5-demo/target/surefire-reports/TEST-jcg.zheng.demo.junit5.SomeClassTest.xml
