image: docker.porscheinformatik.com/eenv/builders/default:jdk-11

stages:
  - build
  - deploy
  - acceptence-tests
  - deploy-idle
  - cleanup

variables:
  OPENSHIFT_SERVER: https://manage.ocp.porscheinformatik.cloud:8443/
  OPENSHIFT_DOMAIN: ext.ocp.porscheinformatik.cloud
  OPENSHIFT_PROJECT: poi-user-koc
  DOCKER_REGISTRY: docker.porscheinformatik.com
  # Configure these variables in Secure Variables:
  # DOCKER_REGISTRY_USER
  # DOCKER_REGISTRY_PASSWORD
  # OPENSHIFT_TOKEN

before_script:
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/koc/angular-spring-heroes:$CI_COMMIT_REF_SLUG" .
    - docker push "$DOCKER_REGISTRY/koc/angular-spring-heroes:$CI_COMMIT_REF_SLUG"
  only:
    - merge_requests
    - master

.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN"
    - oc project $OPENSHIFT_PROJECT
    - |
      function deploy_name() {
        if [[ "$CI_COMMIT_REF_SLUG" == "master" ]]; then
          name='prod'
        else
          name="$CI_COMMIT_REF_SLUG"
        fi
        name=${name:0:45}
        name=${name%-}
        echo "ash-$name"
      }
  script:
    - helm3 repo add porscheinformatik https://helm-charts.int.ocp.porscheinformatik.cloud
    - helm3 upgrade --install --atomic --history-max 5 --namespace ${OPENSHIFT_PROJECT} $(deploy_name) -f deploy/${HELM_VALUES} --set appVersion="v`date +'%Y%m%d-%H%M%S'`" --set image.tag=$CI_COMMIT_REF_SLUG --set route.host=$APP_HOST --set postgresql.postgresPassword="${POSTGRESQL_PASSWORD}" porscheinformatik/web-application

deploy-review:
  <<: *deploy
  stage: deploy
  variables:
    APP_HOST: ash-mr-$CI_MERGE_REQUEST_ID.$OPENSHIFT_DOMAIN
    HELM_VALUES: "values-review.yaml"
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://ash-mr-$CI_MERGE_REQUEST_ID.$OPENSHIFT_DOMAIN
    on_stop: stop-review
  only:
    - merge_requests

acceptence-tests:
  image: cypress/base:10
  stage: acceptence-tests
  variables:
    CYPRESS_baseUrl: https://ash-mr-$CI_MERGE_REQUEST_ID.$OPENSHIFT_DOMAIN
  before_script:
    - cd heroes-acceptence-tests
    - npm i
  script:
    - npm test
  only:
    - merge_requests
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - heroes-acceptence-tests/cypress/videos

deploy-production:
  <<: *deploy
  stage: deploy
  variables:
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
    HELM_VALUES: "values-prod.yaml"
  when: manual
  environment:
    name: production
    url: https://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master

deploy-review-idle:
  <<: *deploy
  stage: deploy-idle
  only:
    - merge_requests
  script:
    - oc idle "$(deploy_name)-web-application"

stop-review:
  <<: *deploy
  stage: cleanup
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - helm3 --namespace ${OPENSHIFT_PROJECT} delete $(deploy_name)
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - merge_requests
