image:
  repository: docker.porscheinformatik.com/koc/angular-spring-heroes
  tag: add-review-tag-in-helm-install
ports:
- name: jolokia
  containerPort: 8778
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 480Mi
