image:
  repository: docker.porscheinformatik.com/koc/angular-spring-heroes
  tag: master
postgresql:
  enabled: true
  postgresUser: heroes
  postgresDatabase: heroes
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 20m
    memory: 480Mi
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 30
